### ISSUE TITLE
Function toString?

### ISSUE THREAD

**Issue by jdalton** [sindresorhus/mimic-fn#1]
Would this be up for mimicking the `toString()` of a function? 

Something I did in Lodash was to preserve the `toString` (when not minified) but also let them know what wrapping was applied.

For example `lodash/fp/map` when coerced to a string reports:

``` js
`function map(collection, iteratee) {
/* [wrapped with _.ary, _.curry, & _.rearg] */
    var func = isArray(collection) ? arrayMap : baseMap;
    return func(collection, getIteratee(iteratee, 3));
}`
```

**Comment by sindresorhus** [comment]
I like that idea, but it wouldn't be as clear when the wrapper is not a Lodash function, but instead named `timing`. How about embedding the source of the wrapper function as a comment?

**Comment by jdalton** [comment]
Can you post a mockup of what you have in mind.

**Comment by sindresorhus** [comment]
With:

```js
function foo() {}
foo.unicorn = '🦄';

function wrapper() {
    return foo() {};
}

mimicFn(wrapper, foo);

console.log(wrapper.toString());
```

The output would be:

```
/*
function wrapper() {
    return foo() {};
}
*/
function foo() {}
```

But looking at it now, it might get very verbose.

I'm still not sure this is worth it at all though. Do people really use `fn.toString()` at all? I only previously used it to reliably get the function name, but that's not needed anymore. Are weover thinkingg an edge-case here?

**Comment by jdalton** [comment]
I think maybe the FP crowd hits the need to inspect their funcs more. There they wrap (curry, rearg, etc.) so what you end up with is a func that doesn't look like what you started with. When I go poking around I tend to just dump the value into the console to see what I'm working with

![](https://cloud.githubusercontent.com/assets/4303/19551535/7761ba88-9660-11e6-94de-15c3dbea89a2.gif)

**Comment by sindresorhus** [comment]
Ok, let's go with the Lodash way then (`/* [wrapped with _.ary, _.curry, & _.rearg] */`).

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/mimic-fn/pull/6 tried to solve this, but went stale. If you intend to work on this, see the feedback in that PR.

**Comment by ehmicky** [comment]
PR at #32
