### ISSUE TITLE
Error on iOS 'Attempting to change access mechanism for an unconfigurable property'

### ISSUE THREAD

**Issue by jeanregisser** [sindresorhus/mimic-fn#10]
Hi,

I got the following exception in a React Native app (iOS) when I added [p-memoize](https://github.com/sindresorhus/p-memoize).

```
2018-11-12 11:33:00.365 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Attempting to change access mechanism for an unconfigurable property.
```

The props that are problematic are `arguments`, `caller`, `length` and `name`.

I'm using it like this: 

```js
import pMemoize from 'p-memoize';

const memoized = pMemoize(async (path, version) => {
 // [...]
});
```

Not yet sure about the best way to fix this for the React Native env.

**Comment by zenflow** [comment]
I have the same problem trying to use this package (transpiled of course, and as a dependency of the `mem` package) in IE11

It seems that this package as-is is not compatible with all host environments

**Comment by sindresorhus** [comment]
This is a Node.js module. I have no intention to add extra code to support IE or React Native, sorry.

**Comment by ehmicky** [comment]
The error on IE11 should now be fixed with the new release.

The one on React native might be fixed when using the [`ignoreNonConfigurable` option](https://github.com/sindresorhus/mimic-fn#ignorenonconfigurable).
