### ISSUE TITLE
[PR proposal] Custom `function.length`

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/mimic-fn#13]
Some users might want to copy all function properties except `length`. For example:

```js
const newFunc = func.bind(null, true)
// newFunc.length should be one fewer than func.length
mimicFn(newFunc)
```

A `length` option could be added to solve this:

```js
const newFunc = func.bind(null, true)
// funcLength is func.length
// If the return value of length() is negative, newFunc.length will be 0
mimicFn(newFunc, { length: funcLength => funcLength - 1 })
```

This could be useful for any function wrapper that modifies function arity through binding, currying, etc.

I can submit a PR if you think it is a good idea.

**Comment by sindresorhus** [comment]
Sure, PR welcome :)

Make sure to mention the use-cases for it when you document it.

**Comment by ehmicky** [comment]
Done in #18

**Comment by sindresorhus** [comment]
Hmm, I've been thinking about this. First, it seems like an obscure use-case, as no one should really depend on `Function#length`, that's an anti-pattern. Second, wouldn't it be simpler to just have a `{length: false}` (to not copy length) option?

**Comment by ehmicky** [comment]
`{length: false}` is a much better idea indeed. Actually I don't think there needs to be an option, `function.length` should just never be copied, as I don't see a reason why anyone would want this.

It is an obscure use-case indeed, but we could make this lightweight by only doing this: when iterating over properties, skip `length`. What do you think?

**Comment by ehmicky** [comment]
Done in #23
