### ISSUE TITLE
Copying `Function.prototype`

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/mimic-fn#15]
Behavior is different depending on whether the function to mimic is an arrow function or not:

```js
const from = function() {}
const to = function() {}
console.log(from.prototype === to.prototype) // false
mimicFn(from, to)
console.log(from.prototype === to.prototype) // true
```

```js
const from = function() {}
const to = () => {}
console.log(from.prototype === to.prototype) // false
mimicFn(from, to)
console.log(from.prototype === to.prototype) // false
```

This is because `Function.prototype` is not defined for arrow functions. `mimic-fn` only iterates over properties that are defined.

This leaves two questions:
  - when `from.prototype` is not defined, should `to.prototype` be deleted?
  - when any property is defined in `to` but not `from`, should it be deleted from `to`?

**Comment by sindresorhus** [comment]
> when from.prototype is not defined, should to.prototype be deleted?

Yes

> when any property is defined in to but not from, should it be deleted from to?

Yes, but it should be clearly documented.

**Comment by ehmicky** [comment]
I will submit a PR for this.

**Comment by ehmicky** [comment]
PR at #28
