### ISSUE TITLE
This does not work with non-writable properties

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/mimic-fn#16]
Classes cannot use `mimic-fn` as the first argument:

```js
mimicFn(class {}, function () {})
```

throws the following error:

```
    Object.defineProperty(to, prop, Object.getOwnPropertyDescriptor(from, prop))
           ^
TypeError: Cannot redefine property: prototype
    at Function.defineProperty (<anonymous>)
```

This is because `Function.prototype` is not `writable` in classes.

`{ get name(): function() {} }` and `{ set name(): function() {} }` are also not `writable`.

I see three possible solutions to this issue. Trying to copy non-`writable` properties could:
  1) throw an error (current behavior, does not work with classes)
  2) be a noop
  3) temporarily set the property as `writable: true`, to make the copy.

**Comment by sindresorhus** [comment]
I don't see the need to support this. Let's throw a useful error. `1`.

**Comment by ehmicky** [comment]
Does this include both classes and `get`/`set` functions?

**Comment by sindresorhus** [comment]
Ah missed that. We should replace getter/setters by using your `3` solution.

**Comment by ehmicky** [comment]
Note that `Function.prototype` is non-configurable, i.e. relies on #17 too.

However the issue is still valid for configurable but non-writable properties.

**Comment by ehmicky** [comment]
I got this wrong. Non-writable properties do not throw errors when `Object.defineProperty()` is used. They only do when they are also non-configurable, which is #17.
