### ISSUE TITLE
This does not work with non-configurable properties

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/mimic-fn#17]
Non-configurable properties cannot be mimicked:

```js
const a = function () {}
Object.defineProperty(a, 'test', { configurable: false })
const b = function () {}
b.test = true
mimicFn(a, b)
```

throws the following error:

```
    Object.defineProperty(to, prop, Object.getOwnPropertyDescriptor(from, prop))
           ^

TypeError: Cannot redefine property: test
    at Function.defineProperty (<anonymous>)
```

Is it correct behavior, or should the property be silently skipped instead?

**Comment by sindresorhus** [comment]
I think throwing is correct. We shouldn't silently pretend it worked. However, it would be useful to be able to specify a list of properties to ignore. `mimicFn(a, b, {ignore: ['test']}`.

**Comment by ehmicky** [comment]
I will submit a PR for `options.ignore`.

**Comment by ehmicky** [comment]
#10 is related to this info.

It seems like React Native and IE11 set some function properties as non-configurable. I.e. under the current behavior but also with the `ignore` option, those environments cannot be supported. If this is still the intended solution, I think we should close #10?

**Comment by sindresorhus** [comment]
> but also with the ignore option, those environments cannot be supported

Why can they not be supported if the user manually ignores the problematic properties?

Honestly though, I couldn't care less about those platforms, so I'm happy to just close #10.

**Comment by ehmicky** [comment]
> Why can they not be supported if the user manually ignores the problematic properties?

This would require the user to conditionally use the `ignore` option:
  - detect the current platform
  - for each failing platform, define the correct `ignore` option values

This might be too much to ask to the user.

However I'm happy with not supporting those platforms.

**Comment by ehmicky** [comment]
The problem is also impacting classes:

```js
class A {}
class B {}
mimicFn(A, B)
```

```
TypeError: Cannot redefine property: prototype
    at Function.defineProperty (<anonymous>)
    at copyProperty (/home/me/mimic-fn/index.js:7:9)
    at mimicFn (/home/me/mimic-fn/index.js:31:3)
```

That's because `Function#prototype` is non-configurable and non-writable. I.e. using `mimicFn()` on two different classes does not work. 

One possible solution would be to never try to copy `prototype`. Because we never can. What do you think?

**Comment by sindresorhus** [comment]
> One possible solution would be to never try to copy prototype. Because we never can. What do you think?

👍

**Comment by ehmicky** [comment]
For the original problem: would any user want to `ignore` some non-configurable properties but not others? Should we add a boolean option `ignoreNonConfigurable` instead, defaulting to `false`?

**Comment by sindresorhus** [comment]
> Should we add a boolean option ignoreNonConfigurable instead, defaulting to false?

Yeah, I think that would be enough.
