### ISSUE TITLE
This does not work with inherited properties

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/mimic-fn#29]
The following example fails:

```js
class A { static func() {} }
class B extends A {}
class C {}

mimicFn(C, B)
t.is(C.func, B.func)
```

This is because we are using `Reflect.ownKeys()` which does not retrieve inherited properties. 

One way to solve this would be to call `Object.setPrototypeOf(C, Object.getPrototypeOf(B))`.

**Comment by sindresorhus** [comment]
> One way to solve this would be to call Object.setPrototypeOf(C, Object.getPrototypeOf(B)).

👍 And should be documented.

**Comment by ehmicky** [comment]
Done in #30
