### ISSUE TITLE
New major release `3.0.0`

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/mimic-fn#38]
Should we make a new release once all the PRs are merged?

Current changelog:

# Breaking changes

- Copy inherited properties of the original function. (#30)
- Do not copy the `length` property. (#23)
- Drop support for Node 6. (#25)
- Remove `module.exports.default`. (#26) If you used to do `require('mimic-fn').default`, you should now use `require('mimic-fn')` directly.

# Features

- `String(wrapper)` now mimics `String(originalFunction)`. A comment is prepended to indicate the original function has been wrapped. (#32) 
- Add boolean option `ignoreNonConfigurable` to ignore the wrapper function's non-configurable properties instead of throwing an error. This defaults to `false`. (#33, #34, #35)
- Allow functions with different `prototype` such as classes, constructor functions and arrow functions. (#31, #36)

# Design

- Add a logo. (#37)

# Maintainers

- Add @ehmicky as an additional maintainer.

**Comment by sindresorhus** [comment]
> Should we make a new release once all the PRs are merged?

Yes, that's the plan.

**Comment by sindresorhus** [comment]
You have npm publish access. Feel free to release v3.

**Comment by ehmicky** [comment]
Just published it :tada:

**Comment by sindresorhus** [comment]
Yay!
