### ISSUE TITLE
Older uglify doesn't support ES6

### ISSUE THREAD

**Issue by zedd45** [sindresorhus/mimic-fn#4]
I'm working on a "legacy" stack that uses Webpack `v1.x.x` (currently `1.13.3`), and [the version of `uglify` I'm using doesn't support `e6`](https://github.com/mishoo/UglifyJS2/issues/659).  

I noticed that the `index.js` file uses [an arrow function to assign the module.exports](https://github.com/sindresorhus/mimic-fn/blob/3703ef8142ce6b7170297e58fee1a14799b79975/index.js#L2).  

Would you accept a PR to ES5ify this, so my webpack doesn't explode with this error: 

```
ERROR in bundle.{hash}.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [./~/mimic-fn/index.js:2,0]
```

I would be happy to submit one.

**Comment by SamVerschueren** [comment]
We aim for Node.js, not the browser. You can find a more detailed explanation here https://github.com/sindresorhus/ama/issues/446.

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
