### ISSUE TITLE
Use GitHub Theme Context to Support Logo in Dark Mode

### ISSUE THREAD

**Issue by Yash-Singh1** [sindresorhus/mimic-fn#44]
Currently the logo is rendered like this in dark mode:

![Screenshot from 2022-06-27 14-22-11](https://user-images.githubusercontent.com/53054099/176019550-44cc84c6-1f8c-471a-b257-3c19ea678d79.png)

https://github.com/github-community/community/discussions/16910

**Comment by ehmicky** [comment]
Good point!
We could also use a white background on the logo instead:

![mimic-fn_white](https://user-images.githubusercontent.com/8136211/179235806-291682e8-3ca0-44c3-a177-c747e74b499f.png)

This would be simpler than creating a separate logo for dark mode.
What do you think @sindresorhus?

**Comment by sindresorhus** [comment]
👍

**Comment by ehmicky** [comment]
Fixed in https://github.com/sindresorhus/mimic-fn/pull/45
